import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/GlobalState'
import Navbar from '@/Components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <GlobalState>
<<<<<<< HEAD
          <Navbar></Navbar>

          <div className=' pt-[75px]'>
=======
        
           <div className=''>
>>>>>>> 579d3ffe6b6e5b60e8ece4e9c9e3fb5f8125a34f
            {children}
          </div>
        </GlobalState>
   
      </body>
    </html>
  )
}
