import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/GlobalState'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FRACTOS',
  description: 'Generated by create next app',
  icons: {
    icon: ['./favicon.ico']
  }
}

export default function RootLayout({ children }) {


  if (typeof window !== 'undefined') {
    // Your client-side code here
  }

  return (
    <html lang="en">

      <Head>
      <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>

        <GlobalState>
          <div className=''>

            {children}
          </div>


        </GlobalState>

      </body>
    </html>
  )
}
