import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/GlobalState'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   className={inter.className}>

        <GlobalState>
<<<<<<< HEAD
           <div className=''>
        
=======
          <Navbar></Navbar>

          <div className=' pt-[75px]'>

>>>>>>> 740c6a143837c8fde29e5461cda43f7e2059030d
            {children}
          </div>


        </GlobalState>

      </body>
    </html>
  )
}
